name: Build and Deploy Docker App

on:
  push:
    branches: [main]  # Trigger only when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t GrowthMetrics .

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Pull latest code (optional if repo is already cloned)
          cd ~/GrowthMetrics

          git pull origin main

          # Stop and remove old container
          docker stop GrowthMetrics || true
          docker rm GrowthMetrics || true

          # Remove old image
          docker rmiGrowthMetrics || true

          # Build and run new container
          docker build -t GrowthMetrics .
          docker run -d -p 5000:5000 --name GrowthMetrics GrowthMetrics

